# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  script = "script"
  src = "src"
  test = "test"
  libs = ["lib"]
  fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./" },
  ]
  cache_path = "cache"
  evm_version = "shanghai"
  solc_version = "0.8.25"
  prompt_timeout = 120

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[etherscan]
  mainnet = { key = "${ETHERSCAN_API_KEY}" }
  holesky = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 115
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true
  single_line_statement_blocks = "multi"
  sort_imports = true

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  holesky = "${HOLESKY_RPC_URL}"
